version: '3.1'

services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test
    container_name: my-mysql-docker-compose
    volumes:
      - mysql-volume:/var/lib/mysql

  my-app:
    build: .
    image: my-app:v1.2
    ports:
      - 8585:9191
    container_name: my-app-docker-compose
    depends_on:
      - db

volumes:
  mysql-volume:
